services:
  backend:
    pull_policy: always

  celery_worker:
    pull_policy: always

  celery_browser_worker:
    pull_policy: always

  celery_beat:
    pull_policy: always

  frontend:
    pull_policy: always
