services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile

  celery_browser_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
